GovWifi/govwifi-smoke-tests

smoke-tests-concourse.yml
Configures the slack integration on failed tests.
Test failure now visible on slack.
=> Adds slack integration on failure

spec/system/signup/signup_spec.rb
We had a smoke test failure on Monday night, as one of the radius failed to authenticate. We believe this was due to the scheduled reboots which occur between 01:00 and 01:15.
We can't control exactly when the smoke tests run, so if they run during this window, we should skip the radius check.
=> Skip radius smoke-tests when rebooting instances

spec/system/signup/signup_spec.rb
Couldn't test this locally so missed that returning isn't valid inside the `it`.
=> Quick fix - returning within `it` block doesn't work.

spec/system/signup/signup_spec.rb
=> We want the radius checks to occur *outside* the window, not inside.

spec/system/admin/locations_page_spec.rb, spec/system/admin/logs_page_spec.rb, spec/system/admin/settings_page_spec.rb, spec/system/admin/shared_context.rb, spec/system/admin/switch_organisation_spec.rb, spec/system/admin/team_page_spec.rb
We're seeing intermittent admin smoke test failures, but it's unclear what the cause is.
This change means the page content is dumped on failure, so we can inspect it and see what's wrong.
=> On admin test failure, output the page body so we can see why it failed.

spec/system/admin/locations_page_spec.rb, spec/system/admin/logs_page_spec.rb, spec/system/admin/settings_page_spec.rb, spec/system/admin/shared_context.rb, spec/system/admin/switch_organisation_spec.rb, spec/system/admin/team_page_spec.rb
Reverts the earlier change, and reimplements.
The previous one only worked if the expectation was what failed. If anything failed prior to that it did not output the error.
Now we're checking in the `after(:each)` block, so it will dump the page on any failure.
=> Make admin errors very verbose

spec/system/admin/shared_context.rb
Refuse the GA tracking cookie
Smoke test data is polluting the analytics.
=> Refuse the tracking cookies, so smoke test don't pollute GA data

smoke-tests-concourse.yml, spec/system/admin/shared_context.rb, spec/system/signup/signup_spec.rb
**WHAT**
Enable smoke tests to be run on production (every 60mins) AND staging (adhoc click to run)
**WHY**
Currently smoke tests just run on production - with many dependabot updates needed the ability to smoke test staging on demand without need to manually do it after hacking codes etc is a no brainer - doing this in code once is roughly the same time as doing it manually once -
=> Make smoke tests run on prod and staging

smoke-tests-concourse.yml
**WHAT**
Make it so each concourse pipeline can only run once at a time
**WHY**
Or we can get clogged up with lots of semi failed builds running at once
e.g.
=> make it so only one instance of each job can run at once

spec/system/signup/signup_spec.rb
Follow up to previous PR, add `\r\n` when checking for newline
Because that's how it comes through in the email.
=> New line in received email is `\r\n` not just `\n`

smoke-tests-concourse.yml
Add `latest` tag to ECR image
An error started occurring saying tag or version must be specified. It can't just be any tag though, has to be `latest` for it to be picked up by the tests.
=> Add tag to ECR image

spec/system/admin/shared_context.rb
Change button text when completing 2FA to "Continue".
Because the change has been made on the admin site.
=> Update button text to match code change.

lib/eapol_test.rb
Change retries from 0 to 2 and timeout from 3 to 9 seconds 
90% of the failed Smoke Tests are when one server does not respond and this is UDP (stateless) after all...
Link to Trello card (if applicable):
=> Make Smoke Tests more forgiving when testing RADIUS servers

spec/system/admin/logs_page_spec.rb
Temporarily disable search page smoke tests
A recent Admin change is causing this to fail, however the functionality is
fine when manually tested. Disabling until I can discuss with the team.
=> Temporarily disable search page smoke tests

smoke-tests-concourse.yml
Remove the reference to 'temp' as in staging-temp environment.
This is now a legacy environment which has been destroyed and replaced by staging proper.
=> remove reference to legacy temp environment

spec/spec_helper.rb, spec/system/admin/logs_page_spec.rb
Reinstate disabled smoke test
Reinstate disabled smoke test
The Logs Page/search smoke test was disabled because is failed as
JQuery was removed from the admin portal.
The test has been fixed by removing an earlier workaround that used
JQuery and now uses capybara.
This also means that headless mode can be used, speeding up the
tests
=> Reinstate smoke tests

smoke-tests-concourse.yml
Use the deploy- secrets for image access for the staging tests
This means that the ECR repository in the production account is used,
rather than the one in the staging account.
Because only the production repository was being updated by the
pipeline, the latest image in the staging repository was quite out
date, and eventually this caused the smoke tests to fail (because out
of date code was being used).
Link to Trello card: https://trello.com/b/9jIWLDIa/govwifi-stand-up-q3-2021
=> Use the deploy- secrets for image access for the staging tests

spec/system/admin/locations_page_spec.rb, spec/system/admin/settings_page_spec.rb, spec/system/admin/team_page_spec.rb
Adapt the Smoke Tests for the removal of the /overview page
It was removed in
https://github.com/alphagov/govwifi-admin/pull/1557
Link to Trello card: https://trello.com/c/Za9sk2oK/2032-remove-overview-page
=> Adapt the Smoke Tests for the removal of the /overview page

spec/system/admin/team_page_spec.rb
Fix the xpath for removing a team member
The invited bit appears by the name, rather than the email address, so
remove it from the selector.
Link to Trello card: https://trello.com/c/qGBxPnU0/2087-changes-to-invite-team-member-and-edit-team-member-page-2
=> Fix the xpath for removing a team member

spec/system/admin/logs_page_spec.rb
We recently changed how to filter logs. This commit updates the
test so it is in line with the new UI
See: https://github.com/alphagov/govwifi-admin/pull/1608
Otherwise the tests will test the old version and break.
=> Update logging smoke test

README.md
Add documentation for generating Google API tokens
The GovWifi smoke tests recently broke when a gmail password was changed. Generating the token was an unnecessarily long and convoluted process. Adding documentation to help with that.
Link to Trello card (if applicable):  https://trello.com/c/TS0mAYay/2282-fix-govwifi-smoketests
=> Add documentation for generating Google API tokens

lib/google_mail.rb
The OOB authentication part of the Google Mail client code is
never used, and as the smoke tests are run in an automated way
will not work even if it did.
Second, the OOB authentication is deprecated by Google at the
start of October 2022 and so we should remove it
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251/backlog?selectedIssue=GW-294
=> Remove OOB authentication

smoke-tests-concourse.yml
Increase the frequency of smoke tests to every 10 minutes
This will give us more granular information how well things are
working.
=> Increase the frequency of smoke tests to every 10 minutes

spec/system/signup/signup_spec.rb
Every now and then the smoke tests fail. An Eapol test would be performed for a username and a password and this would fail against all radius servers. 
After investigating, it was found that the username would appear in the sessions table as 'failed'. The username however would be absent in the userdetails table in the users DB. Further investigations uncovered it _was_ present in the user details table in the _staging_ environment.
This leads us to believe emails are sometimes erroneously read from staging instead of production, leading to this error.
This fix filters messages from a particular environment, thereby fixing the problem
=> Fix intermittent failuers in smoke tests.

spec/system/signup/signup_spec.rb
The signup test sometimes times out. The email does seem to arrive eventually, so we increase the timeout interval.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-447
=> Allow more time for an email to arrive.

lib/env_token_store.rb
Update the name of the root key of the credentials hash
We recently renewed the refresh token which forced us to change the OAuth credentials from 'desktop' to 'web' application type. This means the downloaded credentials hash now has 'web' as the key and not 'settings' This change reflects this.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-622
=> Update the name of the root key of the credentials hash

README.md
Add additional documentation around smoke test infrastructure
Keeping documentation up to date, as these have now been moved.
Jira card:
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?label=GovWifi-SRE&selectedIssue=GW-614
=> Add additional documentation around smoke test infrastructure

Gemfile, Gemfile.lock, Makefile, lib/notify_sms.rb, lib/services.rb, spec/lib/notify_sms_spec.rb, spec/system/signup/sms_journey_spec.rb
Implement the SMS Journey in smoke tests. This uses a new service "GovWifi-Smoketest" in Notify that sends and receives messages to/from GovWifi as though it was a client.
We are currently not live testing the SMS signup journey. This PR gives us more certainty that our service performs
correctly
Link to JIRA card (if applicable):
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-845
=> Sms journey specs

lib/notify_sms.rb
Increase the timeout to wait for Notify SMS messages
The polling loop to check new messages regularly times out and so the time out is increased to make that less likely to happen
=> Increase the timeout to wait for Notify SMS messages

lib/notify_email.rb, lib/notify_sms.rb, spec/lib/notify_email_spec.rb, spec/lib/notify_sms_spec.rb, spec/system/signup/email_journey_spec.rb, spec/system/signup/sms_journey_spec.rb, spec/system/signup/sponsor_journey_spec.rb
Add specs for the Sponsor Journey
We did not smoke test the sponsor journey so far. This test logs in, sends an email and an SMS using the sponsor journey and tests if the credentials can be used to access GovWifi.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-862
=> Add sponsor journey

lib/notify_sms.rb
Increase timeout for receiving SMS messages
The smoke tests regularly fail waiting for SMS messages that arrive later than expected.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-925
=> Increase timeout for receiving SMS messages

spec/system/admin/team_page_spec.rb
With a recent change requiring 2 administrators, there can now be two links with the label "Invite a team member". This change ensures Capybara finds the correct one.
=> Fix duplicate link error in team page specs

lib/notify_email.rb, lib/notify_sms.rb
The smoke tests fail from time to time because it takes longer than expected to receive an SMS or an email.
This commit increases the email timeouts to 5 minutes and the sms timeouts to 10 minutes
=> Increase timeouts to receive emails and SMS

Makefile, openssl.conf, spec/system/signup/eap_tls_journey_spec.rb
Add test for EAP TLS
Ensure EAP TLS works by connecting using a known certificate / key
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-1117
=> Add test for EAP TLS

spec/system/signup/eap_tls_journey_spec.rb
Disable EAP-TLS test
The change has not yet been deployed to production
=> Disable EAP-TLS test

README.md
Added some extra details to the environment variables 
To enable running the test locally and to understand how this all fits together.
[GW-1247](https://technologyprogramme.atlassian.net/browse/GW-1247)
[GW-1247]: https://technologyprogramme.atlassian.net/browse/GW-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GW-1247: Add more env var detail

Gemfile.lock
Reverts alphagov/govwifi-smoke-tests#76
Breaking smoke tests.
=> Revert "Bump selenium-webdriver from 4.9.0 to 4.18.1"

README.md
Add documentation around CBA
We have added Certificate Based Authentication to GovWifi. Added instructions around generating certificates for testing and other relevant information.
Link to Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=5e45277d29e6d00c970616c6&selectedIssue=GW-1801
=> Add documentation around CBA

spec/system/signup/sms_journey_spec.rb
Reenable the sms journey smoke tests
We need to test the sms journey
https://technologyprogramme.atlassian.net/browse/GW-2232
=> Reenable the sms journey smoke tests

spec/support/remove_user_helper.rb, spec/system/signup/email_journey_spec.rb, spec/system/signup/sponsor_journey_spec.rb
2FA token refreshes every 30 seconds, therefore `logout` action requires a sleep time of 30 seconds for the next `login` attempt
By reducing the `logout` action call, smoke tests run time reduced from 8 min to 4 mins 
[GW-2233](https://technologyprogramme.atlassian.net/browse/GW-2233)
=> GW-2233: Optimise running time smoke tests

spec/system/admin/settings_page_spec.rb
The settings page has recently been updated so this test needed to be updated accordingly
=> Update smoke test to check if the FreeRadius IP addresses show
